services:
  postgres:
    image: postgres:15.0-alpine
    hostname: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: testDb
      POSTGRES_USER: someUser
      POSTGRES_PASSWORD: somePassword
